bug fix and  add new NumericUpDownDemo
irihitech/Ursa.Avalonia pull request #170
Opened 2024-03-20 13:31 UTC by heartacker

1. _HorizontalContentAlignment
2. new demo 
3. fix #172 
4. should not SyncTextAndValue while fromTextToValue and clamp

2024-03-20 13:36 UTC, heartacker commented
- linux 
![image](https://github.com/irihitech/Ursa.Avalonia/assets/1876302/6fe56b35-5fd8-4a54-8552-64679099f08b)

![image](https://github.com/irihitech/Ursa.Avalonia/assets/1876302/91fe0a99-733f-40c6-9728-bb3910104d08)

2024-03-20 15:06 UTC, rabbitism commented
❤️ will review tomorrow.

2024-03-21 03:16 UTC, rabbitism requested changes

2024-03-21 03:16 UTC, rabbitism commented on src/Ursa.Themes.Semi/Controls/NumericUpDown.axaml
> +                                Background="Transparent"
Background should not be transparent.

2024-03-21 03:16 UTC, rabbitism commented on src/Ursa/Controls/NumericUpDown/NumericUpDownBase.cs
> +    public static readonly StyledProperty<HorizontalAlignment> HorizontalContentAlignmentProperty = AvaloniaProperty.Register<NumericUpDown, HorizontalAlignment>(
Use `ContentControl.HorizontalContentAlignmentProperty.AddOwner<NumericUpDown>();`

2024-03-21 04:53 UTC, heartacker reviewed
> Background should not be transparent.  

我以为 panel 是嵌套到 ButtonSpinner  ，所以以 ButtonSpinner  为主要，我可以改回去 
<ButtonSpinner                       
                        Background="{TemplateBinding Background}"

2024-03-21 05:41 UTC, rabbitism commented
> > Background should not be transparent.
> 
> 我以为 panel 是嵌套到 ButtonSpinner ，所以以 ButtonSpinner 为主要，我可以改回去 <ButtonSpinner Background="{TemplateBinding Background}"

所以你是需要一个默认无背景的样式是么……根据Semi Design的理念input都是默认灰色背景的

2024-03-21 08:01 UTC, heartacker commented
ready to merge @rabbitism

2024-03-21 09:27 UTC, rabbitism commented
Look good to me so far. But I will have one more fix after merging, it's related to the actual behavior of textbox readonly and drag panel visibility.

2024-03-21 09:28 UTC, rabbitism approved these changes

2024-03-21 09:29 UTC, merged