Add a new control AspectRatioLayout
irihitech/Ursa.Avalonia pull request #480
Opened 2024-11-12 16:05 UTC by WCKYWCKF

The control AspectRatioLayout provides a feature to select control layout based on the aspect ratio of the visual area (Bounds).

2024-11-12 22:22 UTC, WCKYWCKF commented
Providing a default value in AspectRatioLayout.ItemsProperty causes all AspectRatioLayouts to share a List. This issue has been fixed, please help review it.

2024-11-13 07:01 UTC, rabbitism commented
My suggestions:
the `AspectRatioMode` concept kinda limit extensibility. I would recommend introduce something like 
```csharp
public AvaloniaList<double> RatioBreakpoints {get; set; }
```
for Layout,
and 
```csharp
public double MinRatio { get; set; }
public double MaxRaio { get; set; }
```
for layout item. 

when bounds ratio change, find the first item that fall into it's range.
Any thoughts?

2024-11-13 07:59 UTC, WCKYWCKF commented
> My suggestions: the `AspectRatioMode` concept kinda limit extensibility. I would recommend introduce something like
> 
> ```cs
> public double MinRatio { get; set; }
> public double MaxRaio { get; set; }
> ```
> 
> for layout item.
> 
> when bounds ratio change, find the first item that fall into it's range. Any thoughts?

Having users study the relationship between aspect ratio values and shapes can degrade the development experience. 
It might be a good idea to apply the relationship between **Items** and **ItemsSource** to your suggestion.

2024-11-13 11:15 UTC, WCKYWCKF commented
Features have been added, please help review.

2024-11-13 12:00 UTC, rabbitism commented on src/Ursa/Controls/AspectRatioLayout/AspectRatioLayout.cs
> +    public static readonly StyledProperty<AspectRatioMode> CurrentAspectRatioModeProperty =
Should be a readonly DirectProperty.

2024-11-13 12:01 UTC, rabbitism commented on src/Ursa/Controls/AspectRatioLayout/AspectRatioLayout.cs
> +    private void UpdataHistory(bool value)
typo: Updata -> Update

2024-11-13 12:01 UTC, rabbitism commented on src/Ursa/Controls/AspectRatioLayout/AspectRatioLayoutItem.cs
> +    public static readonly DirectProperty<AspectRatioLayoutItem, bool> IsUseAspectRatioRangeProperty =
An internal CLR property is enough?

2024-11-13 12:02 UTC, rabbitism requested changes
Functionally works well, please check these minor issues.

2024-11-13 12:20 UTC, WCKYWCKF commented
Four minor issues have been fixed.

2024-11-14 18:08 UTC, rabbitism approved these changes

2024-11-14 18:08 UTC, merged